import { FILE_CATGORIES as FC } from "./category";

export const FILE_CATEGORIES_LIST: Record<string, string[]> = {
  [FC.image]: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "webp",
    "svg",
    "bmp",
    "tiff",
    "ico",
    "heic",
    "avif",
  ],
  [FC.video]: [
    "mp4",
    "mov",
    "mkv",
    "avi",
    "webm",
    "m4v",
    "flv",
    "wmv",
    "3gp",
    "mpeg",
    "mpg",
  ],
  [FC.audio]: [
    "mp3",
    "wav",
    "aac",
    "ogg",
    "flac",
    "m4a",
    "amr",
    "aiff",
    "opus",
    "wma",
  ],
  [FC.document]: ["pdf", "txt", "rtf", "md", "log"],
  [FC.office]: [
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    "odt",
    "ods",
    "odp",
  ],
  [FC.code]: [
    "json",
    "yaml",
    "yml",
    "xml",
    "toml",
    "ini",
    "env",
    "js",
    "ts",
    "py",
  ],
  [FC.archive]: ["zip", "rar", "7z", "tar", "gz", "tgz", "bz2", "xz"],
  [FC.dataset]: ["csv", "tsv", "parquet", "avro", "sqlite", "db"],
  [FC.font]: ["ttf", "otf", "woff", "woff2", "eot"],
};
