export const SIDEBAR_KEYS = {
  account_identity: "account_identity",
  profile: "profile",
  authentication: "authentication",
  roles_authority: "roles_authority",
  access_tenancy: "access_tenancy",
  tenants: "tenants",
  access_entitlements: "access_entitlements",
  lifecycle: "lifecycle",
  security_trust: "security_trust",
  risk_trust: "risk_trust",
  devices_trust: "devices_trust",
  security_nudges: "security_nudges",
  activity_transparency: "activity_transparency",
  activity_decisions: "activity_decisions",
  transparency: "transparency",
  data_authority: "data_authority",
  data_vault: "data_vault",
  consent_compliance: "consent_compliance",
  safety_continuity: "safety_continuity",
  emergency_recovery: "emergency_recovery",
  help_enablement: "help_enablement",
  security_guidance: "security_guidance",
};
