import "./register/address";
import "./register/audio";
import "./register/checkbox";
import "./register/color";
import "./register/calendar-date";
import "./register/calendar-day";
import "./register/calendar-month";
import "./register/calendar-month-year";
import "./register/calendar-year";
import "./register/dropdown";
import "./register/email";
import "./register/file";
import "./register/image";
import "./register/json";
import "./register/mobile";
import "./register/dropdownMulti";
import "./register/dropdownSimple";
import "./register/otp";
import "./register/password";
import "./register/radio";
import "./register/search";
import "./register/secrurityQuestion";
import "./register/slider";
import "./register/stepper";
import "./register/switch";
import "./register/text";
import "./register/textArea";
import "./register/time";
import "./register/video";
import "./register/url";
import { logger } from "#packages/utils";

export const registerValidations = () => {
  logger.info("Registration of Validation in the Engine is done");
};
