import {
  AddressInput,
  AudioUpload,
  CheckboxGroup,
  DatePicker,
  DayPicker,
  EmailInput,
  FileUpload,
  ImageUpload,
  JsonField,
  MobileInput,
  MonthPicker,
  MonthYearPicker,
  MultipleDropdown,
  OtpField,
  PasswordInput,
  RadioGroup,
  SearchBox,
  SingleDropdown,
  Slider,
  Stepper,
  Switch,
  TextArea,
  TextInput,
  TimePicker,
  VideoUpload,
  YearPicker,
} from "@/atoms";
import type { ComponentType } from "react";

import { FORM_FIELDS_TYPE as FFT } from "../validation/helper/fields";
export type ComponentRegistry = Record<string, ComponentType<any>>;

export const COMPONENT_REGISTRY: ComponentRegistry = {
  [FFT.TEXT]: TextInput,
  [FFT.PASSWORD]: PasswordInput,
  [FFT.DROPDOWN]: SingleDropdown,
  [FFT.MULTI_DROPDOWN]: MultipleDropdown,
  [FFT.EMAIL]: EmailInput,
  [FFT.MOBILE]: MobileInput,
  [FFT.DATE]: DatePicker,
  [FFT.DAY]: DayPicker,
  [FFT.MONTH]: MonthPicker,
  [FFT.MONTH_YEAR]: MonthYearPicker,
  [FFT.YEAR]: YearPicker,
  [FFT.TIME]: TimePicker,
  [FFT.ADDRESS]: AddressInput,
  [FFT.TEXT_AREA]: TextArea,
  [FFT.JSON]: JsonField,
  [FFT.FILE]: FileUpload,
  [FFT.AUDIO]: AudioUpload,
  [FFT.VIDEO]: VideoUpload,
  [FFT.IMAGE]: ImageUpload,
  //   [FFT.SECURITY_QUESTION]: "",
  [FFT.OTP]: OtpField,
  [FFT.CHECKBOX]: CheckboxGroup,
  //   [FFT.COLOR]: "",
  [FFT.RADIO]: RadioGroup,
  [FFT.SEARCH]: SearchBox,
  [FFT.SWITCH]: Switch,
  [FFT.SLIDER]: Slider,
  [FFT.STEPPER]: Stepper,
  //   [FFT.URL]: "",
} as const;
